[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/consumo-agua.jar"

# Configurações do Nixpacks
[nixpacks]
[nixpacks.build]
baseImage = "ubuntu:22.04"