spring:
  application:
    name: consumo-agua

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    br.com.thiago: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic