spring:
  application:
    name: consumo-agua

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${PGUSER:sa}
    password: ${PGPASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    br.com.thiago: ${LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${LOG_SQL:DEBUG}

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info