spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    br.com.thiago: INFO
    org.hibernate.SQL: WARN